#!/bin/bash
#             a8  a7  x86 x64
# ndk-clang   ++. ++. ++. ++.
# linux-gnu   ... ... ... ...
# mingw-llvm  ++. ++. ... ...

lib='lerc'
pkg='Lerc'
dsc='Limited Error Raster Compression'
lic='BSD/GPL-2.0'
src='https://github.com/Esri/lerc.git'
cfg='cmake'
eta='134'

. xbuilder.sh

start

<<'XB64_PATCH'
LS0tIENNYWtlTGlzdHMudHh0CTIwMjEtMDktMTkgMTc6NTQ6MzAuOTYwMTA1NjAwICswMTAwCisr
KyBDTWFrZUxpc3RzLnR4dAkyMDIxLTA5LTE5IDE4OjAxOjQ1Ljc2MDEwNTYwMCArMDEwMApAQCAt
MjcsMTAgKzI3LDE1IEBACiAKIGlmKEJVSUxEX1NIQVJFRF9MSUJTKQogICAgIHNldF90YXJnZXRf
cHJvcGVydGllcyhMZXJjIFBST1BFUlRJRVMgREVGSU5FX1NZTUJPTCBMRVJDX0VYUE9SVFMpCisg
ICAgYWRkX2xpYnJhcnkoTGVyY19zdGF0aWMgU1RBVElDICR7U09VUkNFU30pCisgICAgc2V0X3Rh
cmdldF9wcm9wZXJ0aWVzKExlcmMgTGVyY19zdGF0aWMgUFJPUEVSVElFUyBPVVRQVVRfTkFNRSBM
ZXJjKQorICAgIHNldChMRVJDX1RBUkdFVFMgTGVyYyBMZXJjX3N0YXRpYykKK2Vsc2UoKQorICAg
IHNldChMRVJDX1RBUkdFVFMgTGVyYykKIGVuZGlmKCkKIAogaW5zdGFsbCgKLSAgICBUQVJHRVRT
IExlcmMKKyAgICBUQVJHRVRTICR7TEVSQ19UQVJHRVRTfQogICAgIExJQlJBUlkgREVTVElOQVRJ
T04gJHtDTUFLRV9JTlNUQUxMX0xJQkRJUn0KICAgICBSVU5USU1FIERFU1RJTkFUSU9OICR7Q01B
S0VfSU5TVEFMTF9CSU5ESVJ9CiAgICAgQVJDSElWRSBERVNUSU5BVElPTiAke0NNQUtFX0lOU1RB
TExfTElCRElSfQ==
XB64_PATCH

# Filelist
# --------
# include/Lerc_c_api.h
# include/Lerc_types.h
# lib/pkgconfig/Lerc.pc
# lib/libLerc.so
# lib/libLerc.a