#!/bin/bash

# cpu av8 av7 x86 x64
# NDK +++ +++ +++ +++ clang
# GNU +++  .   .   .  gcc
# WIN +++  .   .  +++ clang/gcc

lib='x265'
dsc='x265 is an open source HEVC encoder'
lic='GPL-2.0'
src='https://github.com/videolan/x265.git'
#src='https://bitbucket.org/multicoreware/x265_git.git'
cfg='cmake'
tls='yasm libnuma-dev'
eta='360'
cbk="ENABLE_CLI"
dir_config='source'
cshk='ENABLE_SHARED'
CFG='-DHIGH_BIT_DEPTH=ON'

lst_inc='x265.h x265_config.h'
lst_lib='libx265'
lst_bin='x265'
lst_oth=''

. xbuilder.sh

$build_bin && CFG+=" -DSTATIC_LINK_CRT=ON"
$build_shared && CSH="-DENABLE_SHARED=ON" || CSH="-DENABLE_SHARED=OFF"
$host_mingw && CFG+=" -DENABLE_PIC=OFF"
$host_arm && CFG+=" -DCROSS_COMPILE_ARM=ON -DENABLE_ASSEMBLY=OFF" || CFG+=" -DCMAKE_ASM_NASM_FLAGS=-w-macro-params-legacy"

start

#cpu patch for arm-mingw archs
# Do NOT edit---------------------------------------------------------------
<<'XB64_PATCH'
LS0tIHNvdXJjZS9DTWFrZUxpc3RzLnR4dAkyMDIxLTEwLTEwIDE4OjQ2OjMyLjQ1NTAwMDAwMCAr
MDEwMAorKysgc291cmNlL0NNYWtlTGlzdHMudHh0CTIwMjEtMTAtMTAgMTg6NTI6MTkuMDgzMzE0
NDAwICswMTAwCkBAIC0yMTksOSArMjE5LDkgQEAKICAgICBlbHNlKCkKICAgICAgICAgYWRkX2Rl
ZmluaXRpb25zKC1zdGQ9Z251Kys5OCkKICAgICBlbmRpZigpCi0gICAgaWYoRU5BQkxFX1BJQykK
KyAgICBpZihOT1QgV0lOMzIgQU5EIEVOQUJMRV9QSUMpCiAgICAgICAgICBhZGRfZGVmaW5pdGlv
bnMoLWZQSUMpCi0gICAgZW5kaWYoRU5BQkxFX1BJQykKKyAgICBlbmRpZigpCiAgICAgaWYoTkFU
SVZFX0JVSUxEKQogICAgICAgICBpZihJTlRFTF9DWFgpCiAgICAgICAgICAgICBhZGRfZGVmaW5p
dGlvbnMoLXhob3N0KQpAQCAtMjM4LDIxICsyMzgsMjUgQEAKICAgICAgICAgICAgIGVuZGlmKCkK
ICAgICAgICAgZW5kaWYoKQogICAgIGVuZGlmKCkKKyAgICBzZXQoUElDICIiKQorICAgIGlmKE5P
VCBXSU4zMikKKyAgICAgICAgc2V0KFBJQyAtZlBJQykKKyAgICBlbmRpZigpCiAgICAgaWYoQVJN
IEFORCBDUk9TU19DT01QSUxFX0FSTSkKICAgICAgICAgaWYoQVJNNjQpCi0gICAgICAgICAgICBz
ZXQoQVJNX0FSR1MgLWZQSUMpCisgICAgICAgICAgICBzZXQoQVJNX0FSR1MgJHtQSUN9KQogICAg
ICAgICBlbHNlKCkKLSAgICAgICAgICAgIHNldChBUk1fQVJHUyAtbWFyY2g9YXJtdjYgLW1mbG9h
dC1hYmk9c29mdCAtbWZwdT12ZnAgLW1hcm0gLWZQSUMpCisgICAgICAgICAgICBzZXQoQVJNX0FS
R1MgLW1hcmNoPWFybXY2IC1tZmxvYXQtYWJpPXNvZnQgLW1mcHU9dmZwIC1tYXJtICR7UElDfSkK
ICAgICAgICAgZW5kaWYoKQogICAgICAgICBtZXNzYWdlKFNUQVRVUyAiY3Jvc3MgY29tcGlsZSBh
cm0iKQogICAgIGVsc2VpZihBUk0pCiAgICAgICAgIGlmKEFSTTY0KQotICAgICAgICAgICAgc2V0
KEFSTV9BUkdTIC1mUElDKQorICAgICAgICAgICAgc2V0KEFSTV9BUkdTICR7UElDfSkKICAgICAg
ICAgICAgIGFkZF9kZWZpbml0aW9ucygtREhBVkVfTkVPTikKICAgICAgICAgZWxzZSgpCiAgICAg
ICAgICAgICBmaW5kX3BhY2thZ2UoTmVvbikKICAgICAgICAgICAgIGlmKENQVV9IQVNfTkVPTikK
LSAgICAgICAgICAgICAgICBzZXQoQVJNX0FSR1MgLW1jcHU9bmF0aXZlIC1tZmxvYXQtYWJpPWhh
cmQgLW1mcHU9bmVvbiAtbWFybSAtZlBJQykKKyAgICAgICAgICAgICAgICBzZXQoQVJNX0FSR1Mg
LW1jcHU9bmF0aXZlIC1tZmxvYXQtYWJpPWhhcmQgLW1mcHU9bmVvbiAtbWFybSAke1BJQ30pCiAg
ICAgICAgICAgICAgICAgYWRkX2RlZmluaXRpb25zKC1ESEFWRV9ORU9OKQogICAgICAgICAgICAg
ZWxzZSgpCiAgICAgICAgICAgICAgICAgc2V0KEFSTV9BUkdTIC1tY3B1PW5hdGl2ZSAtbWZsb2F0
LWFiaT1oYXJkIC1tZnB1PXZmcCAtbWFybSkKCi0tLSBzb3VyY2UvY29tbW9uL2NwdS5vbGQJMjAy
MS0xMC0xMCAxOToyMDozOS4xNjMzMTQ0MDAgKzAxMDAKKysrIHNvdXJjZS9jb21tb24vY3B1LmNw
cAkyMDIxLTEwLTEwIDE5OjIwOjM3LjcyMzMxNDQwMCArMDEwMApAQCAtMzksNyArMzksNyBAQAog
I2luY2x1ZGUgPG1hY2hpbmUvY3B1Lmg+CiAjZW5kaWYKIAotI2lmIFgyNjVfQVJDSF9BUk0gJiYg
IWRlZmluZWQoSEFWRV9ORU9OKQorI2lmIFgyNjVfQVJDSF9BUk0gJiYgIWRlZmluZWQoSEFWRV9O
RU9OKSAmJiAhZGVmaW5lZChfX1dJTjMyX18pCiAjaW5jbHVkZSA8c2lnbmFsLmg+CiAjaW5jbHVk
ZSA8c2V0am1wLmg+CiBzdGF0aWMgc2lnam1wX2J1ZiBqbXBidWY7Cg==
XB64_PATCH

# Filelist
# --------
# include/x265.h
# include/x265_config.h
# lib/pkgconfig/x265.pc
# lib/libx265.so
# lib/libx265.a
# bin/x265
