#!/bin/bash
cat << "EOF"

THE ▀▄ ▄▀   █▀▀▄ █  █ ▀█▀ █   █▀▀▄ █▀▀ █▀▀▄ 
     ▄▀▄ ▀▀ █▀▀▄ █  █  █  █   █  █ █▀▀ █▀▀▄ 
    ▀   ▀   ▀▀▀  ▀▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀  ▀▀▀ ▀  ▀
EOF

jload(){
    lib=$1
    jlib=$(cat .pkglist | jq '."'${lib}'"')
}

jval(){
    echo "${jlib}" | jq --arg key "$1" -r '.[$key] // empty'
}

jload $1
src=$(jval src)     url=$(jval url)     dsc=$(jval dsc)
lic=$(jval lic)     cbk=$(jval cbk)     mki=$(jval mki)
dep=$(jval dep)     cfg=$(jval sys)     mkf=$(jval mkf)
mkc=$(jval mkc)
dir_config=$(jval dir)

shift
. xbuilder.sh $@
CFG=$(eval echo $(echo $p | jq -r '.cfg // empty'))

start